# Generated by Django 6.0.6 on 2026-06-16 02:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_persona', models.CharField(choices=[('FISICA', 'Persona Física'), ('MORAL', 'Persona Moral / Empresa')], default='MORAL', max_length=10)),
                ('nombre', models.CharField(max_length=200)),
                ('rfc', models.CharField(blank=True, max_length=13, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='RFC inválido. Formato esperado: XAXX010101000', regex='^[A-ZÑ&]{3,4}\\d{6}[A-Z0-9]{3}$')])),
                ('razon_social', models.CharField(blank=True, max_length=200)),
                ('contacto_nombre', models.CharField(max_length=150)),
                ('contacto_email', models.EmailField(max_length=254)),
                ('contacto_telefono', models.CharField(blank=True, max_length=20)),
                ('calle', models.CharField(blank=True, max_length=200)),
                ('ciudad', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(blank=True, max_length=100)),
                ('codigo_postal', models.CharField(blank=True, max_length=10)),
                ('pais', models.CharField(default='México', max_length=100)),
                ('estado_cuenta', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('SUSPENDIDO', 'Suspendido')], default='ACTIVO', max_length=15)),
                ('notas', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ContactoAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('cargo', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Contacto adicional',
                'verbose_name_plural': 'Contactos adicionales',
            },
        ),
    ]
