# Generated by Django 6.0.6 on 2026-06-16 02:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_contrato', models.CharField(max_length=50, unique=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('VENCIDO', 'Vencido'), ('CANCELADO', 'Cancelado'), ('RENOVACION', 'En renovación')], default='ACTIVO', max_length=15)),
                ('periodo_facturacion', models.CharField(choices=[('MENSUAL', 'Mensual'), ('TRIMESTRAL', 'Trimestral'), ('ANUAL', 'Anual')], default='MENSUAL', max_length=15)),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('precio_copia_excedente', models.DecimalField(decimal_places=4, default=0.0, help_text='Precio por ciclo excedente de la cuota mensual', max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('incluye_mantenimiento', models.BooleanField(default=True)),
                ('incluye_toner', models.BooleanField(default=True)),
                ('notas', models.TextField(blank=True)),
                ('referencia_documento', models.CharField(blank=True, max_length=300)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Arrendamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo_id', models.PositiveIntegerField(help_text='ID del equipo en ms-equipos')),
                ('equipo_nombre', models.CharField(help_text='Cache del nombre para no depender de ms-equipos', max_length=200)),
                ('equipo_serial', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('DEVUELTO', 'Devuelto'), ('SUSPENDIDO', 'Suspendido')], default='ACTIVO', max_length=15)),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('fecha_devolucion', models.DateField(blank=True, null=True)),
                ('cuota_mensual_ciclos', models.PositiveIntegerField(default=5000, help_text='Ciclos de motor incluidos por mes para este equipo')),
                ('ubicacion', models.CharField(blank=True, max_length=200)),
                ('notas', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arrendamientos', to='contratos.contrato')),
            ],
            options={
                'verbose_name': 'Arrendamiento',
                'verbose_name_plural': 'Arrendamientos',
                'ordering': ['-creado_en'],
                'constraints': [models.UniqueConstraint(fields=('contrato', 'equipo_id'), name='unique_equipo_por_contrato')],
            },
        ),
    ]
